/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutomationSelectionDialog.java
 *
 * Created on 12 avr. 2011, 21:10:40
 */

package modbuspal.automation;

/**
 *
 * @author avincon
 */
public class AutomationSelectionDialog
extends javax.swing.JDialog
{
    private final AutomationListModel automationListModel;
    private boolean isOK = false;

    /** Creates new form AutomationSelectionDialog */
    public AutomationSelectionDialog(AutomationListModel al)
    {
        super();
        setModalityType(ModalityType.APPLICATION_MODAL);
        automationListModel = al;
        initComponents();
    }

    public AutomationSelectionDialog(Automation[] a)
    {
        this( new AutomationListModel(a) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setModel(automationListModel);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        isOK=true;
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed


    public Automation getSelectedAutomation()
    {
        if(isOK==false)
        {
            return null;
        }

        int i = jList1.getSelectedIndex();
        return automationListModel.getAutomation(i);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
