/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * listOfSlavesCellRenderer.java
 *
 * Created on 16 déc. 2008, 15:17:40
 */

package modbuspal.slave;

import modbuspal.main.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @author nnovic
 */
public class ModbusSlavePanel
extends javax.swing.JPanel
implements WindowListener, ModbusSlaveListener
{

    private ModbusSlave modbusSlave = null;
    private ModbusSlaveDialog modbusSlaveDialog = null;

    /** Creates new form listOfSlavesCellRenderer */
    public ModbusSlavePanel(ModbusSlave parent)
    {
        modbusSlave = parent;
        modbusSlaveDialog = new ModbusSlaveDialog(GUITools.findFrame(this), modbusSlave);
        modbusSlaveDialog.addWindowListener(this);
        initComponents();
        setBackground();
    }


    public int getSlaveId()
    {
        return modbusSlave.getSlaveId();
    }

    public void delete()
    {
       if( modbusSlaveDialog != null )
       {
            modbusSlaveDialog.removeWindowListener(this);
            modbusSlaveDialog.setVisible(false);
            modbusSlaveDialog.dispose();
            modbusSlaveDialog = null;
       }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slaveIdLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        enableToggleButton = new javax.swing.JToggleButton();
        showToggleButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        slaveIdLabel.setText(String.valueOf(modbusSlave.getSlaveId()));
        slaveIdLabel.setPreferredSize(new java.awt.Dimension(30, 14));
        add(slaveIdLabel);

        nameTextField.setText(modbusSlave.getName());
        nameTextField.setPreferredSize(new java.awt.Dimension(120, 20));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        add(nameTextField);

        enableToggleButton.setSelected(modbusSlave.isEnabled());
        enableToggleButton.setText("Enable");
        enableToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableToggleButtonActionPerformed(evt);
            }
        });
        add(enableToggleButton);

        showToggleButton.setText("Show");
        showToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showToggleButtonActionPerformed(evt);
            }
        });
        add(showToggleButton);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
    }// </editor-fold>//GEN-END:initComponents

    private void enableToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableToggleButtonActionPerformed
        modbusSlave.setEnabled( enableToggleButton.isSelected() );
    }//GEN-LAST:event_enableToggleButtonActionPerformed

    private void showToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showToggleButtonActionPerformed
        if( showToggleButton.isSelected() == true )
        {
            modbusSlaveDialog.setVisible(true);
        }
        else
        {
            modbusSlaveDialog.setVisible(false);
        }
    }//GEN-LAST:event_showToggleButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ModbusPal.removeModbusSlave(modbusSlave);
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * This method will be triggered when the name text field looses the focus,
     * implicitely meaning that the content is validated by the user. report
     * the content of the text field into the modbus slave.
     * @param evt
     */
    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        String name = nameTextField.getText();
        modbusSlave.changeName(name);
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JToggleButton enableToggleButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JToggleButton showToggleButton;
    private javax.swing.JLabel slaveIdLabel;
    // End of variables declaration//GEN-END:variables

    public void windowOpened(WindowEvent e)
    {
    }

    public void windowClosing(WindowEvent e)
    {
    }

    public void windowClosed(WindowEvent e)
    {
        if( e.getSource() == modbusSlaveDialog )
        {
            //modbusSlaveDialog = null;
            showToggleButton.setSelected(false);
        }
    }

    public void windowIconified(WindowEvent e)
    {
    }

    public void windowDeiconified(WindowEvent e)
    {
    }

    public void windowActivated(WindowEvent e)
    {
    }

    public void windowDeactivated(WindowEvent e)
    {
    }

    @Override
    public void modbusSlaveEnabled(ModbusSlave slave, boolean enabled)
    {
        if(slave==modbusSlave)
        {
            enableToggleButton.setSelected(enabled);
            setBackground(enabled);
        }
    }


    private void setBackground()
    {
        setBackground( modbusSlave.isEnabled() );
    }

    private void setBackground(boolean enabled)
    {
        if( enabled )
        {
            setBackground( javax.swing.UIManager.getDefaults().getColor("Panel.background") );
        }
        else
        {
            setBackground( javax.swing.UIManager.getDefaults().getColor("List.background") );
        }
    }

    @Override
    public void modbusSlaveImplChanged(ModbusSlave slave, int impl)
    {
    }

    @Override
    public void modbusSlaveNameChanged(ModbusSlave slave, String newName)
    {
        nameTextField.setText(newName);
    }

}
