/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpViewer.java
 *
 * Created on 12 janv. 2009, 22:12:04
 */

package modbuspal.doc;

import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author nnovic
 */
public class HelpViewer
extends javax.swing.JDialog
{
    private HTMLEditorKit summaryEditorKit;
    private HTMLEditorKit helpEditorKit;

    /** Creates new form HelpViewer */
    public HelpViewer(java.awt.Frame parent)
    {
        super(parent, false);

        summaryEditorKit = new HTMLEditorKit();
        helpEditorKit = new HTMLEditorKit();

        initComponents();
        splitPane.setDividerLocation( (double)0.33 );
        summaryEditorPane.setEditorKit(summaryEditorKit);
        helpEditorPane.setEditorKit(helpEditorKit);
        
        loadSummary();
        loadPage("welcome.html");
        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryEditorPane = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        helpEditorPane = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ModbusPal Help");
        setMinimumSize(new java.awt.Dimension(600, 400));

        summaryEditorPane.setEditable(false);
        summaryEditorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                summaryEditorPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(summaryEditorPane);
        summaryEditorPane.getAccessibleContext().setAccessibleDescription("text/html");

        splitPane.setLeftComponent(jScrollPane1);

        helpEditorPane.setEditable(false);
        helpEditorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                helpEditorPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane2.setViewportView(helpEditorPane);

        splitPane.setRightComponent(jScrollPane2);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void summaryEditorPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_summaryEditorPaneHyperlinkUpdate

        if( evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED )
        {
            URL url = evt.getURL();
            Object source = evt.getSource();
            
            if( source==summaryEditorPane )
            {
                loadPage(url);
            }
        }
    }//GEN-LAST:event_summaryEditorPaneHyperlinkUpdate

    private void helpEditorPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_helpEditorPaneHyperlinkUpdate

        if( evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED )
        {
            URL url = evt.getURL();
            Object source = evt.getSource();

            if( source==helpEditorPane )
            {
                loadPage(url);
            }
        }
    }//GEN-LAST:event_helpEditorPaneHyperlinkUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane helpEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JEditorPane summaryEditorPane;
    // End of variables declaration//GEN-END:variables



    private void loadSummary()
    {
        try
        {
            URL url = getClass().getResource("summary.html");
            summaryEditorPane.setPage(url);
        }
        catch (Exception ex)
        {
            Logger.getLogger(HelpViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadPage(String filename)
    {
        URL url = getClass().getResource(filename);
        loadPage(url);
    }


    private void loadPage(URL url)
    {
        try {
            helpEditorPane.setPage(url);
        } catch (IOException ex) {
            Logger.getLogger(HelpViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
