/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModbusRequestPanel.java
 *
 * Created on 30 janv. 2009, 08:31:00
 */

package modbuspal.script;

/**
 *
 * @author nnovic
 */
class ScriptManagerPanel
extends javax.swing.JPanel
implements ScriptListener
{
    private ScriptManager script;

    /** Creates new form ModbusRequestPanel */
    public ScriptManagerPanel(ScriptManager source)
    {
        script = source;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        executeToggleButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        filenameLabel = new javax.swing.JLabel();
        pathnameLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new java.awt.GridBagLayout());

        executeToggleButton.setText("Execute");
        executeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 0);
        add(executeToggleButton, gridBagConstraints);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        add(deleteButton, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridBagLayout());

        filenameLabel.setText(script.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 0);
        jPanel1.add(filenameLabel, gridBagConstraints);

        pathnameLabel.setText(script.getFullFilename());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(pathnameLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        return;
    }//GEN-LAST:event_jPanel1MouseEntered

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void executeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeToggleButtonActionPerformed

        if( executeToggleButton.isSelected()==true )
        {
            script.start();
        }

}//GEN-LAST:event_executeToggleButtonActionPerformed

    void execute()
    {
        executeToggleButton.setSelected(true);
        script.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JToggleButton executeToggleButton;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pathnameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void scriptHasEnded(ScriptManager script)
    {
        executeToggleButton.setSelected(false);
    }

}
