/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptInstanciatorPanel.java
 *
 * Created on 30 mars 2009, 13:51:06
 */

package modbuspal.script;

import modbuspal.automation.GeneratorInstanciator;
import modbuspal.automation.InstanciatorFactory;
import modbuspal.main.ModbusPal;

/**
 *
 * @author nnovic
 */
public class ScriptInstanciatorPanel
extends javax.swing.JPanel
{
    private ScriptInstanciator instanciator;

    /** Creates new form ScriptInstanciatorPanel */
    public ScriptInstanciatorPanel(ScriptInstanciator def)
    {
        instanciator = def;
        initComponents();
    }

    boolean contains(ScriptInstanciator si)
    {
        return (si==instanciator);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classnameLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        classnameLabel.setText(instanciator.getClassName());
        add(classnameLabel);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // add the handler to the factory:
        ModbusPal.removeAllGenerators(instanciator.getClassName());
        InstanciatorFactory.remove(instanciator);
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classnameLabel;
    private javax.swing.JButton deleteButton;
    // End of variables declaration//GEN-END:variables

}
