/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptManagerTab.java
 *
 * Created on 22 mars 2009, 13:47:30
 */

package modbuspal.script;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modbuspal.main.ListLayout;
import modbuspal.main.ModbusPal;

/**
 *
 * @author avincon
 */
public abstract class ScriptManagerTab
extends javax.swing.JPanel
{
    private ScriptManagerDialog parentDialog;

    /** Creates new form ScriptManagerTab */
    public ScriptManagerTab(ScriptManagerDialog parent)
    {
        parentDialog = parent;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        listScrollPane = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(addButton);

        add(buttonsPanel, java.awt.BorderLayout.NORTH);

        listPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("List.background"));

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        listPanel.setLayout( new ListLayout() );
        listScrollPane.setViewportView(listPanel);

        add(listScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // open a file chooser dialog in order to select a python file
        JFileChooser openDialog = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Python file", "py");
        openDialog.setFileFilter(filter);
        openDialog.showOpenDialog(this);

        File pythonFile = openDialog.getSelectedFile();
        if( pythonFile==null )
        {
            parentDialog.setStatus("Cancelled by user.");
            return;
        }

        // Create a new Script manager for this script:
        ModbusPal.addScript(pythonFile);
    }//GEN-LAST:event_addButtonActionPerformed

    void add(ScriptManager manager)
    {
        // create a panel for this manager
        ScriptManagerPanel panel = new ScriptManagerPanel(manager);
        manager.addScriptListener(panel);
        listPanel.add(panel);

        // refresh list
        listScrollPane.validate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listScrollPane;
    // End of variables declaration//GEN-END:variables

}
