/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WorkInProgressDialog.java
 *
 * Created on 9 avr. 2009, 13:20:24
 */

package modbuspal.main;

/**
 *
 * @author nnovic
 */
public class WorkInProgressDialog
extends javax.swing.JDialog
{

    /** Creates new form WorkInProgressDialog */
    public WorkInProgressDialog(java.awt.Frame parent, String title, String message)
    {
        super(parent, true);
        setTitle(title);
        initComponents();
        messageLabel.setText(message);
        GUITools.align(parent, this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 100));

        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("MESSAGE.");
        getContentPane().add(messageLabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables

}
