/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModbusMasterDialog.java
 *
 * Created on 4 janv. 2009, 12:47:46
 */

package modbuspal.master;

import java.util.ArrayList;
import java.util.List;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import modbuspal.automation.Automation;
import modbuspal.link.ModbusLink;
import modbuspal.main.AddSlaveDialog;
import modbuspal.main.ModbusPalListener;
import modbuspal.main.ModbusPalProject;
import modbuspal.main.ModbusPalPane;
import modbuspal.slave.ModbusSlave;
import modbuspal.slave.ModbusSlaveAddress;

/**
 *
 * @author nnovic
 */
public class ModbusMasterDialog
extends javax.swing.JDialog
implements ModbusPalListener
{
    private final ModbusPalPane modbusPalPane;
    private ModbusPalProject modbusPalProject;
    private ModbusMasterRoot modbusMasterRoot;
    private DefaultTreeModel mmTreeModel;
    private ArrayList<Thread> threads;
    private boolean isRunning = false;
    
    /** Creates new form ModbusMasterDialog */
    public ModbusMasterDialog(ModbusPalPane p)
    {
        modbusPalPane = p;
        setProject(p.getProject());
        threads = new ArrayList<Thread>();
        initComponents();
        initTree();
    }

    public void setProject(ModbusPalProject p)
    {
        if( modbusPalProject!=null)
        {
            modbusPalProject.removeModbusPalListener(this);
        }
        modbusPalProject = p;
        if(modbusPalProject!=null)
        {
            modbusPalProject.addModbusPalListener(this);
        }
    }
    
    private void initTree()
    {
        // remove all tree nodes
        jTree1.removeAll();
        
        // add the root
        modbusMasterRoot = new ModbusMasterRoot();
        mmTreeModel = new DefaultTreeModel(modbusMasterRoot);
        
        jTree1.setModel(mmTreeModel);
    }
    
    
    
    
    private void addNewTaskWizard()
    {
        NewTaskDialog ntd = new NewTaskDialog(null, true);
        ntd.setVisible(true);
        if( ntd.isOK() == true )
        {
            // obtain data from the form
            String taskName = ntd.getTaskName();
            
            // create new task
            ModbusMasterTask mmt = new ModbusMasterTask();
            mmt.setTaskName(taskName);
            
            modbusPalProject.addModbusMasterTask(mmt);
        }
    }
    

    private void addNewTargetWizard(ModbusMasterTask parent)
    {
        // create dialog for target selection
        AddSlaveDialog asd = new AddSlaveDialog("Target slave(s)");
        asd.setVisible(true);
        if( asd.isAdded() == false )
        {
            return;
        }
        
        // obtain data from the form
        ModbusSlaveAddress[] targets = asd.getSlaveIds();
        String targetName = asd.getSlaveName();
        
        // create new target node in the tree
        ModbusMasterTarget mmt = new ModbusMasterTarget();
        mmt.setTargetName(targetName);
        mmt.setTargetList(targets);
        
        // add the new node in the tree
        parent.add(mmt);
        jTree1.setSelectionPath( new TreePath( mmt.getPath() ) );
    }
    
    
    
    private void addNewRequestWizard( ModbusMasterTarget parent )
    {
        // create dialog for request selection
        ModbusRequestDialog mrd = new ModbusRequestDialog();
        mrd.setVisible(true);
        if( mrd.isOK() == false )
        {
            return;
        }
        
        ModbusMasterRequest mmr = mrd.getRequest();
        parent.add(mmr);
        jTree1.setSelectionPath( new TreePath( mmr.getPath() ) );
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(addButton);

        removeButton.setText("Remove");
        buttonsPanel.add(removeButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        TreePath selection = jTree1.getSelectionPath();
        if( selection != null )
        {
            Object lastCpnt = selection.getLastPathComponent();
            if( lastCpnt instanceof ModbusMasterRoot )
            {
                addNewTaskWizard();
            }
            else if( lastCpnt instanceof ModbusMasterTask )
            {
                addNewTargetWizard( (ModbusMasterTask)lastCpnt );
            }
            else if( lastCpnt instanceof ModbusMasterTarget )
            {
                addNewRequestWizard( (ModbusMasterTarget)lastCpnt );
            }
        }
        else
        {
            addNewTaskWizard();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    
    public boolean isRunning()
    {
        return isRunning;
    }
    
    public void start(final ModbusLink link)
    {
        isRunning = true;
        
        // retrieve the list of tasks
        List<ModbusMasterTask> tasks = modbusPalProject.getModbusMasterTasks();
        
        // create a thread for eack task
        for(final ModbusMasterTask task : tasks)
        {
            Thread t = new Thread( new Runnable()
            {
                @Override
                public void run() 
                {
                    task.run(link);
                }
            });
            threads.add(t);
        }
        
        // start all threads
        for(Thread t : threads)
        {
            t.start();
        }
        
    }

    public void stop()
    {
        // interrupt all threads
        for(Thread t : threads)
        {
            t.interrupt();
        }
        
        threads.clear();
        isRunning = false;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void modbusSlaveAdded(ModbusSlave slave)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modbusSlaveRemoved(ModbusSlave slave)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void automationAdded(Automation automation, int index) 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void automationRemoved(Automation automation)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void pduProcessed() 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void pduException() 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void pduNotServiced() 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modbusMasterTaskRemoved(ModbusMasterTask mmt) 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modbusMasterTaskAdded(ModbusMasterTask mmt) 
    {
        // add new task to the tree
        modbusMasterRoot.add(mmt);
        TreeNode[] path = mmTreeModel.getPathToRoot(mmt);
        TreePath tp = new TreePath(path);
        jTree1.setSelectionPath(tp);
    }

}
