/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModbusRequestPanel.java
 *
 * Created on 30 janv. 2009, 08:31:00
 */

package modbuspal.master;

import java.awt.Color;
import modbuspal.main.ModbusRequest;
import java.awt.Frame;

/**
 *
 * @author nnovic
 */
public class ModbusRequestPanel
extends javax.swing.JPanel
implements MasterListener
{
    private ModbusRequest modbusRequest;

    /** Creates new form ModbusRequestPanel */
    public ModbusRequestPanel(Frame parent, ModbusRequest req)
    {
        modbusRequest = req;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        enableToggleButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        functionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        slaveLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new java.awt.GridBagLayout());

        enableToggleButton.setSelected(true);
        enableToggleButton.setText("Enable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 0);
        add(enableToggleButton, gridBagConstraints);

        deleteButton.setText("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        add(deleteButton, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Function:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        functionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        functionLabel.setText(modbusRequest.getFunction());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 3);
        jPanel1.add(functionLabel, gridBagConstraints);

        jLabel1.setText("Slave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 1);
        jPanel1.add(jLabel1, gridBagConstraints);

        quantityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quantityLabel.setText(String.valueOf(modbusRequest.getQuantity()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 4);
        jPanel1.add(quantityLabel, gridBagConstraints);

        slaveLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        slaveLabel.setText(String.valueOf(modbusRequest.getSlaveId()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 4);
        jPanel1.add(slaveLabel, gridBagConstraints);

        jLabel4.setText("Quantity:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 1);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel3.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 1);
        jPanel1.add(jLabel3, gridBagConstraints);

        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressLabel.setText(String.valueOf(modbusRequest.getAddress()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 1, 3, 4);
        jPanel1.add(addressLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        return;
    }//GEN-LAST:event_jPanel1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JToggleButton enableToggleButton;
    private javax.swing.JLabel functionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel slaveLabel;
    // End of variables declaration//GEN-END:variables

    public void masterHasEnded(ModbusMaster master)
    {
    }

    public void masterHasStarted(ModbusMaster master)
    {
    }

    public void masterLinkHasBeenSetup(ModbusMaster aThis)
    {
    }

    public void masterLinkIsLost(ModbusMaster aThis)
    {
    }

    public void replyReceived(ModbusRequest request)
    {
        if(request==modbusRequest)
        {
            setBackground(Color.WHITE);
        }
    }

    public void requestTransmitted(ModbusRequest request)
    {
        if(request==modbusRequest)
        {
            setBackground(Color.RED);
        }
    }
}
